repo_url: https://github.com/Requisitos-de-Software/2025.1-FGTS/tree/main
repo_name: 2025.1-FGTS

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.keys

site_name: FGTS

theme:
  name: material
  favicon: assets/logo_fgts.png
  logo: assets/logo_fgts.png
  features:
    - navigation.instant
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/weather-night
        name: Escuro

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Claro

  language: pt-BR

extra_css: [stylesheets/extra.css]

nav:
  - Home: index.md
  - Atas de Reunião:
    - Ata 1: atas/ata_07_04.md
    - Ata 2: atas/ata_11_04.md
    - Ata 3: atas/ata_25_04.md
    - Ata 4: atas/ata_01_05.md
  - Entregas:
    - Entrega 1: Entregas/Entrega_01.md
  - Planejamento:
    - Aplicativo: Planejamento/Aplicativo.md
    - Cronograma: Planejamento/Cronograma.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Metodologia: Planejamento/Metodologia.md
    - Plano de Reuniões: Planejamento/Plano-de-Reunioes.md
  - Pré-Rastreabilidade:
    - Rich Picute: Pré-Rastreabilidade/Rich_Picture.md
  - Elicitação:
    - Elicitação: Elicitacao/Elicitacao.md
  - Verificação:
    - Grupo +1:
      - Entrega 1: Inspecao-do-Grupo-mais1/Inspecao-Entrega-1.md