repo_url: https://github.com/Requisitos-de-Software/2025.1-FGTS/tree/main
repo_name: 2025.1-FGTS

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - footnotes
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

site_name: 2025.1-FGTS

theme:
  name: material
  favicon: assets/logo_fgts.png
  logo: assets/logo_fgts.png
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/weather-night
        name: Escuro

    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Claro

  language: pt-BR

extra_css: [stylesheets/extra.css]

nav:
  - Home: index.md
  - Atas de Reunião:
    - Ata 1: atas/ata_07_04.md
    - Ata 2: atas/ata_11_04.md
    - Ata 3: atas/ata_25_04.md
    - Ata 4: atas/ata_01_05.md
  - Planejamento:
    - Aplicativo: Planejamento/Aplicativo.md
    - Cronograma: Planejamento/Cronograma.md
    - Ferramentas: Planejamento/Ferramentas.md
    - Metodologia: Planejamento/Metodologia.md
    - Plano de Reuniões: Planejamento/Plano-de-Reunioes.md
  - Entrega:
    - Entrega 1: Entregas/Entrega_01.md
  - Inspeção do Grupo +1:
    - Inspeção Entrega 1: Inspeção-do-Grupo-+1/Inspeção-Entrega-1.md
  - Pré-Rastreabilidade:
    - Rich Picute: Pré-Rastreabilidade/Rich_Picture.md
